import "react-toastify/dist/ReactToastify.css";
import { ToastContainer, toast } from "react-toastify";
import localFont from "next/font/local";
import "./globals.css";
import { Poppins } from "next/font/google";
import mongoose from "mongoose";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const poppins = Poppins({
  weight: ["100", "900"],
});

export const metadata = {
  title: "Noubodiez Porjects",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
      <ToastContainer />
    </html>
  );
}
